name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: denolib/setup-deno@master
      with:
        deno-version: 0.40.0

    - name: Run tests
      run: deno test --allow-write --allow-read
